from abc import ABC, abstractmethod

class ActionDispatcher(ABC):
    @abstractmethod
    def play_pause(self): ...
    @abstractmethod
    def next_track(self): ...
    @abstractmethod
    def prev_track(self): ...
    @abstractmethod
    def volume_up(self): ...
    @abstractmethod
    def volume_down(self): ...
    @abstractmethod
    def mute_toggle(self): ...
